# This config file outlines the pipeline that will run when a PR has been opened.

version: 2.1

jobs:
  lint-and-test:
    docker:
      - image: cimg/python:3.13.5
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install
      - run:
          name: Linting
          command: |
            make lint
      - run:
          name: Testing
          command: |
            make test

  build-docker-image:
    docker:
      - image: cimg/base:2023.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: docker build . -t usage-reporter:latest
      - run:
          name: Simple test image is functional
          command: docker run --rm usage-reporter --help
  
  e2e-send-to-postgres:
    docker:
      - image: cimg/python:3.13.5
      - image: cimg/postgres:18.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: circleci_usage
    steps:
      - checkout
      # TODO: use workspace from lint-and-test instead of reinstalling dependencies
      - run:
          name: Install dependencies
          command: |
            make install
            make install-cli
      - run:
          name: Send to PostgreSQL
          command: |
            circleci-usage-reporter send-to-postgres \
              --input .circleci/test-data.csv \
              --database circleci_usage \
              --user postgres \
              --password postgres \
              --summary
      - run:
          name: Assert expected row count imported
          command: |
            IMPORTED_ROWS=$(PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -d circleci_usage -At -c "SELECT COUNT(*) FROM circleci_usage;")
            if [ "$IMPORTED_ROWS" -ne 2000 ]; then
              echo "❌ Expected 2000 rows, but found $IMPORTED_ROWS in circleci_usage table!"
              exit 1
            else
              echo "✅ Found expected $IMPORTED_ROWS rows in circleci_usage table."
            fi

workflows:
  testing:
    jobs:
      - lint-and-test
      - build-docker-image
      - e2e-send-to-postgres:
          requires:
            - lint-and-test