apiVersion: 1

datasources:
  - name: CircleCI Postgres
    uid: circleci-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: usage
    database: circleci_usage
    isDefault: true
    editable: false
    secureJsonData:
      password: usage
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false

  - name: CircleCI Prometheus
    uid: circleci-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 15s
